from nltk.corpus import stopwords

stop_words = stopwords.words('english') +             ['et', 'al', 'fig', 'figs', 'figure', 'table', 'also',
            'using', 'found', 'observed', 'however', 'previous', 'study',
            'although', 'studies', 'several', 'showed', 'could', 
            'performed', 'known', 'methods', 'whether', 'materials',
            'known', 'analyzed', 'within', 'show', 'respectively', 
            'thus', 'therefore', 'tested', 'among', 'abstract', 
            'introduction', 'may', 'shown', 'results', 'interestingly',
            'either', 'similarly', 'furthermore', 'consistently', 
            'neither', 'one', 'two', 'three', 'four', 'five', 'six',
            'seven', 'eigh', 'nine', 'ten', 'eleven', 'twelve', 
            'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen',
            'eighteen', 'nineteen', 
            'supplemental', 'almost', 'generally', 'underlying', 'play',
            'pivotal', 'remain', 'whose',
            'finally' , 'name', 'albeit', 'notably', 'corresponding', 'used', 'obtained', 'total', 'panel', 'seen',
'left', 'right', 'another', 'ability', 'significantly', 'upon', 'observations', 'detecting', 'unveil',
'hypothesized', 'yet', 'whereas', 'capture', 'middle', 'determined', 'added', 'amounts', 'visualized',
'bottom', 'involved', 'aim', 'highly', 'specific', 'caused', 'marked', 'suggest', 'expected', 'combined', 
'wished', 'explore', 'hypothesis', 'dramatically', 'involves', 'verified', 'proper', 'existence',
'finding', 'establish', 'direct', 'previously', 'mediated', 'remained', 'directly', 'studied', 'indeed',
'individual', 'robustly', 'suggests', 'important', 'supported', 'seem', 'judged', 'much', 'hence',
'regardless', 'must', 'seems', 'findings', 'achieved', 'offer', 'explanation', 'already', 'evidence',
'reported', 'bring', 'usual', 'so-called', 'fashion', 'especially', 'would', 'allow', 'require', 'present',
'first', 'frequently', 'many', 'contribute', 'understanding', 'causing', 'like', 'third', 
'interesting', 'showing', 'various', 'certain', 'particular', 'general', 'described', 'according',
'manufacturers', 'instructions', 'scientific', 'content', 'times', 'page', 'onto', 'processed',
'standard', 'procedures', 'following', 'primary', 'biotechnology', 'generated', 'system', 'provider',
'infected', 'infection', 'time', 'see', 'supplementary', 'note', 'online', 'authors',
'noted', 'represented', 'define', 'apparent', 'appearance', 'cases', 'recognizable', 'case', '4th', '5th',
'right', 'compare', 'picture', 'data', 'log2', 'represents', 'full', 'ref',
'high-resolution', 'real-time', 'defined', 'find', 'proven', 'routine', 'databases', 'literature',
'remaining', 'affecting',
             'whose', 'elusive', 'reveal', 'plays', 'ago', 'others', 'presents', 'correspond', 
'corresponds', 'examined', 'detected', 'straightforward', 'reproducible', 'relevance',
'demonstrating', 'suggested', 'exhibited', 'suggesting', 'likely', 
 #           'mutation', 'cell', 'mutations', 'cells',
            ]


